### ISSUE TITLE
Error: "cannot have more than one connection on the same port"

### ISSUE THREAD

**Issue by sumasrao** [litespeedtech/lsquic#104]
Hi, 

I have built and installed lsquic on Ubuntu 16.04 and am trying to use this example to try parallel connections:
./http_client -H www.litespeedtech.com -s 443 \
                -p / -P file-256M -M POST -n 3 -r 10

But using -n with anything other than 1 gives me this error "cannot have more than one connection on the same port". 

Is there any configuration I may be missing? Please help me to get this to work.

**Comment by dtikhonov** [comment]
This is a limitation of some of the QUIC versions when used by the client.  In particular, Google QUIC versions Q046 and Q050 -- and Q043, when used with TCID option is used (it is by default) -- there is no way to differentiate which connection is which from the packets themselves because the server won't include the CID.

The problem you're having is that by default, *all* versions are enabled by default.  You can select which versions to enable using the `-o` command-line flags.  For example: `-o version=h3-25`.

This could be better documented.

**Comment by sumasrao** [comment]
It works fine with the -o option. Thanks.
