### ISSUE TITLE
Can the function lsquic_conn_make_stream return a "lsquic_stream_t *"?

### ISSUE THREAD

**Issue by cang-mang** [litespeedtech/lsquic#115]
The function lsquic_engine_connect can return a "lsquic_conn_t *", but why the function lsquic_conn_make_stream is void and we must get the "lsquic_stream_t *" from the callback function?

**Comment by dtikhonov** [comment]
The reason for this behavior is that sometimes a stream cannot be created due to peer-imposed limits on opened streams. Currently, if the limit has been reached and `lsquic_conn_make_stream()` is called, the stream creation is postponed; the `on_new_stream()` callback is called when creating another stream is safe again (when another stream is closed).

One alternative would be to return a special status, or perhaps a callback, when immediate stream creation is not possible. This has not proved necessary to us.  Do you have a compelling use case?
