### ISSUE TITLE
Intra-IETF QUIC/HTTP/3 version negotiation is broken due to ALPN

### ISSUE THREAD

**Issue by mickel8** [litespeedtech/lsquic#180]
Hi, 
I am not sure if this is a bug or I am doing something wrong but invoking
```
./http_client -s www.google.com -p /
```
results in 
```
15:01:47.795 [WARN] [QUIC:967430E39685E122] handshake: encrypt crypto context at level forw-secure not initialized
```
and nothing more is returned i.e. there isn't any HTTP response in my console.

Looking into wireshark I cannot see any payload sent to me or from to google. I also tried to test it with
`quic.tech:4433` or `quic.tech:8443` but none of them works for me.

 All tests are passing so I believe my installation of `lsquic` is correct.

Am I missing something? I am using version from master.

**Comment by dtikhonov** [comment]
The problem is that Google uses h3-29, whereas lsquic by default will use the highest version it implements, which is h3-31.  There is no version negotiation in IETF QUIC v1, so handshake fails.  The warning message is a bug in lsquic: it fails to encrypt a packet with a _CONNECTION_CLOSE_ frame in it.

To make the long story short, add `-o version=h3-29` to your command line and things will work.

**Comment by dtikhonov** [comment]
I take it back: version negotiation is attempted, but lsquic does not do it properly:

```
sh$ ./http_client -s www.google.com -p / -l event=debug
11:46:17.631 [DEBUG] [QUIC:F6149AB853641E1B] event: connection created
11:46:17.631 [DEBUG] [QUIC:F6149AB853641E1B] event: version negotiation: proposed version FF00001F
11:46:17.631 [DEBUG] [QUIC:F6149AB853641E1B] event: created packet 0; flags: version=1, nonce=0, conn_id=1
11:46:17.631 [DEBUG] [QUIC:F6149AB853641E1B] event: generated CRYPTO frame: offset: 0, size: 235
11:46:17.631 [DEBUG] [QUIC:F6149AB853641E1B] event: sent packet 0, type Initial, crypto: clear, size 1200, frame types: PADDING CRYPTO, ecn: 0, spin: 1; kp: 0, path: 0, flags: 1073840906
11:46:17.645 [DEBUG] [QUIC:F6149AB853641E1B] event: version negotiation: supports version FF00001D
11:46:17.645 [DEBUG] [QUIC:F6149AB853641E1B] event: version negotiation: supports version FF00001B
11:46:17.645 [DEBUG] [QUIC:F6149AB853641E1B] event: version negotiation: supports version Q050
11:46:17.645 [DEBUG] [QUIC:F6149AB853641E1B] event: version negotiation: supports version Q046
11:46:17.645 [DEBUG] [QUIC:F6149AB853641E1B] event: version negotiation: supports version Q043
11:46:17.645 [DEBUG] [QUIC:F6149AB853641E1B] event: packet 0 repackaged for resending as packet 1
11:46:17.645 [DEBUG] [QUIC:F6149AB853641E1B] event: sent packet 1, type Initial, crypto: clear, size 1200, frame types: PADDING CRYPTO, ecn: 0, spin: 1; kp: 0, path: 0, flags: 1107395338
11:46:17.655 [DEBUG] [QUIC:F6149AB853641E1B] event: version negotiation: agreed version FF00001D
```

**Comment by dtikhonov** [comment]
What lsquic does is resend the ClientHello using the negotiated version of QUIC, ID-29, but wrong ALPN, h3-31.  It should regenerate ClientHello and include the correct ALPN, h3-29, for the version negotiation to work.

I don't expect this to be fixed, because a) this mechanism is likely to become defunct when QUIC v1 is released and b) version negotiation is not necessary for an HTTP/3 client, because the other side's version is communicated to it via the _Alt-Svc_ HTTP header.  Nevertheless, let's leave this bug open for now as a record.
