### ISSUE TITLE
Why is the tutorial tut.c so slow?

### ISSUE THREAD

**Issue by derekbsnider** [litespeedtech/lsquic#229]
Hi there,

I just came across this project, and started watching the tutorial video, and built all the required libraries and tut.c, and once I got it working, decided to do some simple timing tests, and it seems really slow:

```
[root@324dfa1f2214 lsquic-tutorial]# ./tut -c mycert-cert.pem -k mycert-key.pem 127.0.0.1 12345 &
[root@324dfa1f2214 lsquic-tutorial]# time echo hi | ./tut 127.0.0.1 12345 >& /dev/null

real	0m0.068s
user	0m0.007s
sys	0m0.003s

[root@324dfa1f2214 lsquic-tutorial]# time cat tut.c | ./tut 127.0.0.1 12345 >& /dev/null

real	0m0.578s
user	0m0.203s
sys	0m0.252s
```

Is this to be expected, or am I doing something wrong here?

**Comment by dtikhonov** [comment]
I'd expect it to be slow due to [this code](https://github.com/dtikhonov/lsquic-tutorial/blob/master/tut.c#L827):

```c
/* Read one byte at a time -- when user hits enter, send line to server */
static void
tut_read_stdin (EV_P_ ev_io *w, int revents)
```

In addition, you will notice that each line is a request to the server.  You're making 1418 requests to the server in the second example.  I'd say finishing in under 600ms is not too bad.  :slightly_smiling_face:
