### ISSUE TITLE
Why PING FRAME need retransmitted in lsquic ?

### ISSUE THREAD

**Issue by Lingtaonju** [litespeedtech/lsquic#237]
Dear sir,  I wander why the PING Frame need retransmitted in lsquic, what'e the idea of this design? 
```
/* [draft-ietf-quic-transport-20], Section 13.2 */
/* We bend some rules and retransmit BLOCKED, MAX_DATA, MAX_STREAM_DATA,
 * MAX_STREAMS, STREAM_BLOCKED, and STREAMS_BLOCKED frames instead of
 * regenerating them.  This keeps the code simple(r).
 */
#define IQUIC_FRAME_RETX_MASK (  \
    ALL_IQUIC_FRAMES & ~(QUIC_FTBIT_PADDING|QUIC_FTBIT_PATH_RESPONSE    \
            |QUIC_FTBIT_PATH_CHALLENGE|QUIC_FTBIT_ACK|QUIC_FTBIT_TIMESTAMP))
```

As in the draft there is no such requirement.

```
PING and PADDING frames contain no information, so lost PING or
PADDING frames do not require repair. (FROM 34)

```

**Comment by dtikhonov** [comment]
We retransmit PING frames because we don't want a lost packet to cause an idled out connection.  PINGs are sent by the client to keep the connection open after some time.  If the packet is lost and the client does not retrasmit it, the connection will likely close before it's time to send the next ping.

**Comment by Lingtaonju** [comment]
OK , but two problems here:
firstly, the implement  is inconsistent with the draft;
secondly, with lsquci as the client, the implement inconsistent with the server.

So, how about make the ping interval shorter ?

**Comment by dtikhonov** [comment]
1. You're right, we should not retransmit the _PING_ frame.
2. By "inconsistent," do you mean thtat the server does not send pings by default, while the client does?

With regards to the ping interval: you can change the default value using the `es_ping_period` setting option.

**Comment by Lingtaonju** [comment]
> 1. You're right, we should not retransmit the _PING_ frame.
> 2. By "inconsistent," do you mean thtat the server does not send pings by default, while the client does?
> 
> With regards to the ping interval: you can change the default value using the `es_ping_period` setting option.


1. "inconsistent" just means that:  the quic server such as nginx, will not retransmit the ping, but  lsquic doses.
2.  My suggestion is that: for lsquic , in order to  `keep the connection open after some time` , you can shorter the ping interval but not make ping Retransmitted.

**Comment by dtikhonov** [comment]
I would classify these as "no action:"

- If we followed what nginx did, we'd still be beta-testing our QUIC support instead of running it in production for the past four years.
- A server does not even send pings, so the point is moot.
- lsquic provides configuration knobs to adjust both ping and idle times.

**Comment by litespeedtech** [comment]
In a real world case, we found retransmitting PING frame is a better and more reliable approach to keep connection alive than shorter PING interval but not retransmit lost PING, so, we will keep that logic. that's the final decision.
