### ISSUE TITLE
Pluggable SSL backend for use on mips and armhf

### ISSUE THREAD

**Issue by pfeatherstone** [litespeedtech/lsquic#96]
The boringssl dependency does not build on mips-i version 1 or armhf. Maybe you don't care, in which case, fair enough. Thought you might want to know.

**Comment by pfeatherstone** [comment]
I could post this issue on boringssl page but they explicitly say not to use boringssl as a third party library. It's tailored for in-house google products...

**Comment by pfeatherstone** [comment]
Actually, boringssl doesn't even accept issues.

**Comment by pfeatherstone** [comment]
On mips-i, I get error messages like :

boringssl/crypto/hrss/asm/poly_rq_mul.S:319: Error: unrecognized opcode `push %rbp'
boringssl/crypto/hrss/asm/poly_rq_mul.S:321: Error: bad register expression

and so on

**Comment by pfeatherstone** [comment]
On armhf, I get error messages like :

boringssl/crypto/cipher_extra/aead_test.cc:545:54: error: requested alignment 64 is larger than 8 [-Werror=attributes]
   alignas(64) uint8_t key[EVP_AEAD_MAX_KEY_LENGTH + 1];

**Comment by pfeatherstone** [comment]
Again, I can appreciate this is a boringssl issue

**Comment by dtikhonov** [comment]
Thank you for letting us know.  We haven't tried building on these platforms before.

I agree it would be nice to be able to use OpenSSL with lsquic in addition to BoringSSL.  This, however, requires a significant amount of effort that can be spent better elsewhere (from our perspective).  As always, PRs are welcome!

**Comment by pfeatherstone** [comment]
Maybe some of the embedded tls/crypto libraries like mbedtls would be well suited. They build everywhere

**Comment by dtikhonov** [comment]
Yeah, it would be nice to have pluggable SSL backends a la curl.

**Comment by JonasVautherin** [comment]
> I agree it would be nice to be able to use OpenSSL with lsquic in addition to BoringSSL. This, however, requires a significant amount of effort

Can you be more specific than that? I tried to link against OpenSSL instead of BoringSSL, and some includes were missing that I did not find in OpenSSL. I did not go further, but if you know it would require a significant amount of effort, maybe I won't even bother. Do you have some pointers on what you are using that is BoringSSL-specific (and why you are using that)?

One of the issues I have is that I don't necessarily want to distribute the SSL library myself, I'd rather depend on the system one. And typically that's OpenSSL :slightly_smiling_face:.

**Comment by dtikhonov** [comment]
It has been several years since we've decided to use BoringSSL and we have not investigated this further.  I could not give you the specifics without diving into this myself: I simply don't remember them.  Also, your goal of using stock OpenSSL is not possible for IETF QUIC, you will need a patched version by Tatsuhiro Tsujikawa.

On the other hand, I of course see the value in lsquic being able to use OpenSSL as well as BoringSSL.  If you would like to collaborate (where naturally you do most of the work and we advise if you get stuck on some lsquic-iness :slightly_smiling_face: ), I would gladly do so.  We can make a branch and work on that.

**Comment by JonasVautherin** [comment]
Right, I understand. I cannot commit to too much, but as a first step I could try to make it such that lsquic finds BoringSSL through `find_package(OpenSSL REQUIRED)`, so that it can be exchanged with OpenSSL easily at the build system level.

However, I'm a bit confused: you say it's not possible to use OpenSSL with IETF QUIC, but it would work with lsquic? :thinking: 

Is there a change that those patches by Tatsuhiro Tsujikawa will ever get upstream? Is that intended at all? I mean, HTTP/3 will be over QUIC, so I was guessing that OpenSSL/LibreSSL/BoringSSL would all work with it at some point...

**Comment by dtikhonov** [comment]
lsquic started before IETF QUIC.  At that time, it supported gQUIC only.  Now it supports both gQUIC and IETF QUIC protocols.  You will need the aforementioned patch for the latter.

I believe this is the PR: https://github.com/openssl/openssl/pull/8797
